Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -1,12 +1,3 @@
-schedules:
-- cron: "34 22 * * *"
-  displayName: Daily midnight build
-  branches:
-    include:
-    - main
-    
-
-
 
 trigger: none
 pool: 
@@ -22,45 +13,33 @@ variables:
 - template: /variables/global_vars.yml
 
 stages:
+- stage: validate_jdk_preview_lab
+  jobs:
+  - job: validate_jdk_preview_lab 
+    displayName: Validate Preview Lab Pipeline Run Results
+    pool: server
+    steps:
+    - task: ManualValidation@0
+      timeoutInMinutes: 1 # task times out in 1 day
+      inputs:
+        notifyUsers: |
+          mehrdad.hazeghi@nuance.com
+        instructions: 'Important: Activate ONLY AFTER confirming the Lab pipeline has run and verifying the run results/logs!!!'
+        onTimeout: 'resume'
+  - job: fail_pipeline
+    displayName: Fail Pipeline On Manual Validation Refusal
+    container: terraform_image_container
+    dependsOn: validate_jdk_preview_lab
+    condition: failed()
+    steps:
+    - script: |
+        echo "manual validaton of lab preview pipeline failed, exiting the pipeline"
+        exit 1
 - stage: RunInContainerStage
   jobs:
   - job: RunInContainerJob
     timeoutInMinutes: 1
     steps:
     - script: |
-        uname -a
-        docker ps
-        printenv | grep reason
-        printenv
-        echo "starting the job ---------------------------------------"
-        echo "yum --------------------"
-        which yum
-        yum install epel-release -y 2> /dev/null
-        yum install jq -y 2> /dev/null
-        which jq
-        /usr/bin/jq --version
-        echo "yum done ----------------------------"
-        yum --version
-        echo "in container ---------------------------------"
-        pwd
-        ls -ltR
-        ps -edaf
-        echo ${{ variables.TIME_ZONE }}
-        curl ${{ variables.APACHE_HTTPD_MIRROR_PATH }} | grep -oP '(?<=>httpd-).*(?=.tar.bz2)' > mirror_htppd_list_file
-        cat ./mirror_htppd_list_file
-        latest_httpd_release_on_mirror_repo=`sort -V mirror_htppd_list_file | tail -1`
-        echo ${latest_httpd_release_on_mirror_repo}
-        echo "done"
-        echo $(Pipeline.Workspace) # /__w/1
-        echo build directory - The local path on the agent where all folders for a given build pipeline are created. This variable has the same value as Pipeline.Workspace.
-        echo build directory $(Agent.BuildDirectory)
-        echo home directory $(Agent.HomeDirectory)
-        echo agent job name $(Agent.JobName)
-        echo agent temp directory $(Agent.TempDirectory)
-        echo agent work folder $(Agent.WorkFolder)
-        echo Build.SourcesDirectory - The local path on the agent where your source code files are downloaded. For example: c:\agent_work\1\s
-        echo Build.SourcesDirectory $(Build.SourcesDirectory) 
-        echo Build.StagingDirectory - The local path on the agent where any artifacts are copied to before being pushed to their destination. For example: c:\agent_work\1
-        echo Build.StagingDirectory $(Build.StagingDirectory)
-        date
+        echo "RunInContainerStage RunInContainerStage RunInContainerStage RunInContainerStage RunInContainerStage RunInContainerStage"
 
